
name: testing via pytest
run-name: ${{ github.actor }} is running pytest testing
on: [push]
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Startup name
      - uses: actions/checkout@v3

      - name: another one
      - uses: actions/setup-python@v4
      
      - name: Install dependencies
      - run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
      - name: Run tests
      - run: pytest tests

