
name: testing via pytest
run-name: ${{ github.actor }} is running pytest testing
on: [push]
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4


      - name: checking directories
        run: ls -al 

      - name: check requirements
        run: cat git_actions/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
      - name: Install django
        run: pip install django

      - name: Run tests
        run: pytest git_actions/tests

